recheck

diff --git a/.github/workflows/remote-browser.yml b/.github/workflows/remote-browser.yml
--- a/.github/workflows/remote-browser.yml
+++ b/.github/workflows/remote-browser.yml
@@ -121,12 +121,18 @@ jobs:
           path: testReports
 
       - name: Copy Test Report
-        run: cp testReports/index.html index.html
+        run: |
+          if [ ! -f testReports/index.html ]; then
+            echo "Test report not found!"
+            exit 1
+          fi
+          cp testReports/index.html index.html
 
       - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
+        uses: actions/upload-pages-artifact@v4
         with:
           path: 'index.html'
+
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
